//
//  MenuInterfaces.swift
//  Blu
//
//  Created by Aranza Manriquez Alonso on 25/12/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum MenuNavigationOption {
}

protocol MenuWireframeInterface: WireframeInterface {
    func navigate(to option: MenuNavigationOption)
}

protocol MenuViewInterface: ViewInterface {
    func successGetImage(response: DogImageResponse)
    func failureGetImage(messageError: String)
}

protocol MenuPresenterInterface: PresenterInterface {
    func performGetImage()
}

protocol MenuInteractorInterface: InteractorInterface {
    func executeGetImage(onSuccess successCallBack: ((_
                                                      reponse: DogImageResponse) -> Void)?, onFailure failureCallBack: ((_
                                                                                                                         errorMessage: String) -> Void)?,
                                                        request: Parameters)
}
