//
//  MenuInteractor.swift
//  Blu
//
//  Created by Aranza Manriquez Alonso on 25/12/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire

final class MenuInteractor {
    var queue: OperationQueue
    
    init() {
        self.queue = OperationQueue()
        self.queue.maxConcurrentOperationCount = 2
    }
}

// MARK: - Extensions -

extension MenuInteractor: MenuInteractorInterface {
    func executeGetImage(onSuccess successCallBack: ((DogImageResponse) -> Void)?, onFailure failureCallBack: ((String) -> Void)?, request: Alamofire.Parameters) {
        do {
            self.queue.addOperation (APICallManager(url: ServicesName.dogImage, method: .get, body: nil, parametersURL: request, onSuccess: { (response) in
                do {
                    let jsonDecoder = JSONDecoder()
                    jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase
                    let response = try jsonDecoder.decode(DogImageResponse.self, from: response)
                    successCallBack?(response)
                } catch let error {
                    failureCallBack?(error.localizedDescription)
                }
            }, onFailure: { (errorMessage) in
                failureCallBack?(errorMessage)
            }))
        }
    }
    
}
