//
//  MenuWireframe.swift
//  Blu
//
//  Created by Aranza Manriquez Alonso on 25/12/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MenuWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "MenuImages", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instiateViewController(ofType: MenuViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = MenuInteractor()
        let presenter = MenuPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MenuWireframe: MenuWireframeInterface {

    func navigate(to option: MenuNavigationOption) {
    }
}
