//
//  MenuPresenter.swift
//  Blu
//
//  Created by Aranza Manriquez Alonso on 25/12/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MenuPresenter {

    // MARK: - Private properties -

    private unowned let _view: MenuViewInterface
    private let _wireframe: MenuWireframeInterface
    private let _interactor: MenuInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: MenuWireframeInterface, view: MenuViewInterface, interactor: MenuInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension MenuPresenter: MenuPresenterInterface {
    func performGetImage() {
        let emptyRequest: [String: Any] = [:]
        _interactor.executeGetImage(onSuccess: { response in
            if response.status == "success" {
                self._view.successGetImage(response: response)
            } else {
                self._view.failureGetImage(messageError: response.status)
            }
        }, onFailure: { errorMessage in
            self._view.failureGetImage(messageError: errorMessage)
        }, request: emptyRequest)
    }
    
    
}
