//
//  LoginPresenter.swift
//  Blu
//
//  Created by Aranza Manriquez Alonso on 25/12/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginPresenter {

    // MARK: - Private properties -

    private unowned let _view: LoginViewInterface
    private let _wireframe: LoginWireframeInterface
    private let _interactor: LoginInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: LoginWireframeInterface, view: LoginViewInterface, interactor: LoginInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension LoginPresenter: LoginPresenterInterface {
    func goImages() {
        _wireframe.navigate(to: .goImages)
    }
    
    func performLogin(request: LoginRequest) {
        _interactor.executeLogin(onSuccess: { response in
            self._view.successfulLogin(user: response)
        }, onFailure: { errorMessage in
            print(errorMessage)
        }, body: request)
    }
}
